import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'app';
  letra = [];

  ngOnInit(): void {
    this.gerarLetra();
  }

  gerarLetra() {
    const linhas = this.obterInteiroAleatorio(10, 30);
    const frases = this.obterFrases();
    this.letra = [];
    for (let i = 0; i < linhas; i++) {
      this.letra.push(frases[this.obterInteiroAleatorio(0, frases.length)]);
    }
  }

  obterInteiroAleatorio(min, max) {
    return Math.floor(Math.random() * (max - min + 1)) + min;
  }

  obterFrases() {
    return ['Eu não sou o senhor do tempo, mas eu sei que vai chover',
    'Me sinto muito bem quando fico com você',
    'Eu tenho habilidade de fazer histórias tristes',
    'Virarem melodia, vou vivendo o dia a dia',
    'Na paz, na moral, na humilde, busco só sabedoria',
    'Aprendendo todo dia, me espelho em você',
    'Corro junto com você, vivo junto com você',
    'Faço tudo por você',
    'Seguindo em frente com fé e atenção',
    'Continuo na missão continuo por você e por mim',
    'Porque quando a casa cai',
    'Não dá pra fraquejar, quem é guerreiro tá ligado',
    'Que guerreiro é assim',
    'O tempo passa e um dia a gente aprende',
    'Hoje eu sei realmente o que faz a minha mente',
    'Eu vi o tempo passar, vi pouca coisa mudar',
    'Então tomei um caminho diferente',
    'Tanta gente equivocada faz mau uso da palavra',
    'Falam, falam o tempo todo, mas não tem nada a dizer',
    'Mas eu tenho santo forte, é incrível a minha sorte',
    'Agradeço todo tempo por ter encontrado você',
    'O tempo é rei, e a vida é uma lição',
    'E um dia a gente cresce',
    'E conhece nossa essência e ganha experiência',
    'E aprende o que é raiz, então cria consciência',
    'Tem gente que reclama da vida o tempo todo',
    'Mas a lei da vida é quem dita o fim do jogo',
    'Eu vi de perto o que neguinho é capaz por dinheiro',
    'Eu conheci o próprio lobo na pele de um cordeiro',
    'Infelizmente a gente tem que tá ligado o tempo inteiro',
    'Ligado nos pilantra e também nos bagunceiro',
    'E a gente se pergunta por que a vida é assim?',
    'É difícil pra você e é difícil pra mim',
    'Eu não sou o senhor do tempo, mas eu sei que vai chover',
    'Me sinto muito bem quando fico com você',
    'Eu tenho habilidade de fazer histórias tristes',
    'Virarem melodia vou vivendo o dia-a-dia',
    'Na paz, na moral, na humilde busco só sabedoria',
    'Aprendendo todo dia me espelho em você',
    'Corro junto com você, vivo junto com você, faço tudo por você',
    'Vivendo nesse mundo louco hoje só na brisa',
    'Viver pra ser melhor também é jeito de levar a vida',
    'O tempo passa e um dia a gente aprende',
    'Hoje eu sei realmente o que faz a minha mente',
    'Eu vi o tempo passar e pouca coisa mudar',
    'Então tomei um caminho diferente',
    'Tanta gente equivocada faz mal uso da palavra',
    'Falam, falam o tempo todo mas não tem nada a dizer',
    'Mas eu tenho santo forte é incrível a minha sorte',
    'Agradeço todo tempo ter encontrado você',
    'Vem que o bom astral vai dominar o mundo!',
    'Eu já briguei com a vida, hoje eu vivo bem com tudo mundo aí',
    'Na maior moral Charlie Brown!',
    'Vivendo nesse mundo louco hoje só na brisa',
    'Viver pra ser melhor também é um jeito de levar a vida',
    'Tirou a roupa, entrou no mar',
    'Pensei: Meu Deus',
    'Que bom que fosse',
    'Tu me apresenta essa mulher',
    'Meu irmão, te dava até um doce',
    'Sem roupa ela é demais',
    'Também por isso',
    'Eu creio em Deus',
    'Meu bom, Meu Deus',
    'Meu bom, me traz',
    'Ainda bem que eu trouxe',
    'Até meu guarda-sol',
    'Tenho toda tarde',
    'Tenho a vida inteira',
    'Já se foi aquele tempo',
    'Da ladeira, irmão',
    'Já que se foi aquele tempo',
    'Da ladeira, irmão',
    'Meu escritório é na praia',
    'Eu tô sempre na área',
    'Mas eu não sou',
    'Da tua láia, não!',
    'Meu escritório é na praia',
    'Eu tô sempre na área',
    'Mas eu não sou',
    'Daquela láia, não!',
    'Então',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Meu Deus me dê um motivo',
    'Pois eu pago tanto mico',
    'Ela me ignora',
    'Na esperança eu ainda fico',
    'Eu tô fritando aqui',
    'Vou entregar, não aguento mais',
    'Mas se eu não falar hoje',
    'Talvez nunca a veja mais',
    'O dia passa',
    'Horas se estendem',
    'As pessoas ao redor',
    'Nunca me entendem',
    'O dia passa',
    'Horas se estendem',
    'As pessoas ao redor',
    'Nunca me entendem',
    'Então!',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Aheeê!',
    'O dia passa',
    'Horas se estendem',
    'As pessoas ao redor',
    'Nunca me entendem',
    'O dia passa',
    'Horas se estendem',
    'As pessoas ao redor',
    'Nunca me entendem',
    'Tirou a roupa, entrou no mar',
    'Pensei: Meu Deus',
    'Que bom que fosse',
    'Tu me apresenta essa mulher',
    'Meu irmão, te dava até um doce',
    'Sem roupa ela é demais',
    'Também por isso',
    'Eu creio em Deus',
    'Meu bom, Meu Deus',
    'Meu bom, me traz',
    'Ainda bem que eu trouxe',
    'Até meu guarda-sol',
    'Tenho toda tarde',
    'Tenho a vida inteira',
    'Já se foi aquele tempo',
    'Da ladeira, irmão',
    'Já que se foi aquele tempo',
    'Da ladeira, irmão',
    'Meu escritório é na praia',
    'Eu tô sempre na área',
    'Mas eu não sou',
    'Da tua láia, não!',
    'Meu escritório é na praia',
    'Eu tô sempre na área',
    'Mas eu não sou',
    'Daquela láia, não!',
    'Então!',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Deixe viver, deixe ficar',
    'Deixe estar como está',
    'Aheeê!',
    'Aheeê!',
    'Aheeê!',
    'Saca só',
    'As flores são bonitas em qualquer lugar do mundo',
    'Muita gente tem forma, mas não tem conteúdo',
    'Agora eu sei exatamente o que fazer',
    'Bom recomeçar, poder contar com você',
    'Pois eu me lembro de tudo, irmão',
    'Eu estava lá também',
    'Um homem quando está em paz',
    'Não quer guerra com ninguém',
    'Eu segurei minhas lágrimas',
    'Pois não queria demonstrar a emoção',
    'Já que estava ali só pra observar',
    'E aprender um pouco mais sobre a percepção',
    'Eles dizem que é impossível encontrar o amor',
    'Sem perder a razão',
    'Mas pra quem tem pensamento forte',
    'O impossível é só questão de opinião',
    'E disso os loucos sabem',
    'Só os loucos sabem',
    'Disso os loucos sabem',
    'Só os loucos sabem',
    'Toda positividade eu desejo a você',
    'Pois precisamos disso nos dias de luta',
    'O medo cega os nossos sonhos',
    'O medo cega os nossos sonhos',
    'Menina linda, eu quero morar na sua rua',
    'Você deixou saudade',
    'Você deixou saudade',
    'Quero te ver outra vez',
    'Quero te ver outra vez',
    'Você deixou saudade',
    'Agora eu sei exatamente o que fazer',
    'Vou recomeçar, poder contar com você',
    'Pois eu me lembro de tudo, irmão',
    'Eu estava lá também',
    'Um homem quando está em paz',
    'Não quer guerra com ninguém',
    'Canto minha vida com orgulho',
    'Na minha vida nem tudo acontece',
    'Mas quanto mais a gente rala, mais a gente cresce',
    'Hoje estou feliz porque eu sonhei com você',
    'E amanhã posso chorar por não poder te ver mais',
    'O seu sorriso vale mais que um diamante',
    'Se você vier comigo, aí nóis vamo adiante',
    'Com a cabeça erguida e mantendo a fé em Deus',
    'O seu dia mais feliz vai ser o mesmo que o meu',
    'A vida me ensinou a nunca desistir',
    'Nem ganhar, nem perder, mas procurar evoluir',
    'Podem me tirar tudo que tenho',
    'Só não podem me tirar as coisas boas',
    'Que eu já fiz pra quem eu amo',
    'E eu sou feliz e canto',
    'O universo é uma canção',
    'E eu vou que vou',
    'História, nossas histórias',
    'Dias de luta, dias de glória',
    'Histórias, nossas histórias',
    'Dias de luta, dias de glória',
    'Histórias, nossas histórias',
    'Dias de luta, dias de glória',
    'História, nossas histórias',
    'Dias de luta, dias de glória',
    'Oh, minha gata, morada dos meus sonhos',
    'Todo dia, se eu pudesse, eu ia estar com você',
    'Eu já te via muito antes nos meus sonhos',
    'Eu procurei a vida inteira por alguém como você',
    'Por isso eu canto minha vida com orgulho',
    'Com melodia, alegria e barulho',
    'Eu sou feliz e rodo pelo mundo',
    'Sou correria, mas também sou vagabundo',
    'Mas hoje dou valor de verdade',
    'Pra minha saúde e pra minha liberdade',
    'Que bom te encontrar nessa cidade',
    'Esse brilho intenso me lembra você',
    'História, nossas histórias',
    'Dias de luta, dias de glória',
    'Histórias, nossas histórias',
    'Dias de luta, dias de glória',
    'Histórias, nossas histórias',
    'Dias de luta, dias de glória',
    'História, nossas histórias',
    'Dias de luta, dias de glória',
    'Hoje estou feliz',
    'Acordei com o pé direito',
    'E eu vou fazer de novo',
    'E vou fazer muito bem feito',
    'Sintonia',
    'Telepatia',
    'Comunicação pelo córtex',
    'Boom',
    'Bye, bye',
    'Eles querem que você se sinta mal',
    'Pois assim eles se sentem bem',
    'Eu nasci pobre, mas não nasci otário',
    'Eu é que não caio no conto do vigário',
    'Eu tenho fé em Deus pra resolver qualquer parada',
    'Chega com respeito na minha quebrada',
    'Eu não vim pra me explicar',
    'Eu vim pra confundir',
    'Eu não vim pra me explicar',
    'Vem cá, seu cu de burro, eu vou te dar um esculacho',
    'Sua atitude é de playboy porque sua vida é muito fácil',
    'Vencer na vida no mundão é pra quem tem coragem',
    'Um dia eu levo ela pra ver o pôr-do-sol na laje',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Me basta que venha do surf!',
    'Me basta que venha do skate!',
    'Basta que venha do coração!',
    'Basta que venha da mente',
    'Me basta que venha do surf!',
    'Me basta que venha do skate!',
    'Basta que venha do coração!',
    'Basta que venha da mente',
    'Eles são gente',
    'Mas não são gente',
    'Como a gente',
    'Eles são gente',
    'Mas não são gente',
    'Como a gente',
    'Meu estilo de vida',
    'Liberta minha mente',
    'Completamente louco',
    'Mas um louco consciente',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Agora sei',
    'O quanto é precioso',
    'O nosso tempo a gente tem',
    'Que dar valor',
    'Certas coisas',
    'Não têm preço',
    'O fato é que a gente',
    'Tem que se preservar',
    'Viver intensamente',
    'Com a cabeça no lugar',
    'Não, eu não me sinto mal',
    'Eu sobrevivo a todo lixo',
    'Todo ódio, com amor',
    'Eu sou o valor',
    'Das coisas simples',
    'Eu dou valor',
    'Pras coisas simples',
    'Não, eu não me sinto mal',
    'Eu quero mais é que eles queimem',
    'Na fogueira das vaidades',
    'Eu dou valor pras coisas simples',
    'Eu sou o valor das coisas simples',
    'Mas, me diz então',
    'O que da vida posso ter?',
    'Como o mundo deve ser?',
    'Com as balizas do nosso sistema',
    'Me diz então',
    'O que da vida posso ter?',
    'Eu tenho fé em Deus',
    'Pra resolver qualquer problema',
    'Eu nasci pobre, mas não nasci otário',
    'Eu é que não caio no conto do vigário',
    'Eu tenho fé em Deus pra resolver qualquer parada',
    'Chega com respeito na minha quebrada',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Tamo aí na atividade!',
    'Me basta que venha do surf!',
    'Me basta que venha do skate!',
    'Me basta que venha do coração',
    'Basta que venha da mente',
    'Me basta que venha do surf!',
    'Me basta que venha do skate!',
    'Me basta que venha do coração',
    'Basta que venha da mente',
    'Eles são gente',
    'Mas não são gente',
    'Como a gente',
    'Eles são gente',
    'Mas não são gente',
    'Como a gente',
    'Meu estilo de vida',
    'Liberta minha mente',
    'Eu sou completamente louco',
    'Mas um louco consciente',
    'Minha mente',
    'Nem sempre tão lúcida',
    'É fértil e me deu a voz',
    'Minha mente',
    'Nem sempre tão lúcida',
    'Fez ela se afastar',
    'Mas ela vai voltar',
    'Mas ela vai voltar',
    'Ela não é',
    'Do tipo de mulher',
    'Que se entrega na primeira',
    'Mas melhora na segunda',
    'E o paraíso é na terceira',
    'Ela tem força',
    'Ela tem sensibilidade',
    'Ela é guerreira',
    'Ela é uma deusa',
    'Ela é mulher de verdade',
    'Ela é daquelas',
    'Que tu gosta na primeira',
    'Se apaixona na segunda',
    'E perde a linha na terceira',
    'Ela é discreta',
    'E cultua bons livros',
    'E ama os animais',
    'Tá ligado, eu sou o bicho',
    'Minha mente',
    'Nem sempre tão lúcida',
    'É fértil e me deu a voz',
    'Minha mente',
    'Nem sempre tão lúcida',
    'Fez ela se afastar',
    'Mas ela vai voltar',
    'Mas ela vai voltar',
    'Deixa eu te levar',
    'Pra ver o mundo, baby',
    'Deixa eu te mostrar',
    'O melhor que eu posso ser',
    'Deixa eu te levar',
    'Pra ver o mundo, baby',
    'Deixa eu te mostrar',
    'O melhor que eu posso ser',
    'Fazer da vida',
    'O que melhor possa ser',
    'Traçar um rumo novo',
    'Em direção ao sol',
    'Me sinto muito bem',
    'Quando vejo o pôr-do-sol',
    'Só pra fazer nascer a lua',
    'Minha mente',
    'Nem sempre tão lúcida',
    'É fértil e me deu a voz',
    'Minha mente',
    'Nem sempre tão lúcida',
    'Fez ela se afastar',
    'Mas ela vai voltar',
    'Mas ela vai voltar',
    'Mas ela vai voltar',
    'Mas ela vai voltar',
    'Essa é uma história de amargar',
    'Conheci uma garota, meu irmão, vou lhe falar',
    'Tudo que ela quer, o pai dela dá',
    'Desde casa em Ubatuba ao AP no Guarujá',
    'Fim de festa olho pra ela, ela sorri pra mim',
    'Me secou a noite inteira',
    'Ela só pode estar afim',
    'Ela tem carro importado e telefone celular',
    'Eu só tenho uma magrela e um AP no BNH',
    'Eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'Eu falo, eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'O pai dela riu de mim porque o meu carro é popular',
    'E ainda me deu uma notícia de desanimar',
    'Rapaz, você não é bom pra minha filha, não',
    'Quem é teu pai? Quem é você? O que que você faz? Vou investigar você',
    'Fim de festa olho pra ela, ela sorri pra mim',
    'Me secou a noite inteira',
    'Ela só pode estar afim',
    'Ela tem carro importado e telefone celular',
    'Eu só tenho uma magrela e um AP no BNH',
    'Eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'Eu falo, eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'Eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'Eu falo, eu falo tudo que ela gosta de escutar',
    'Deve ser por isso que ela vem me procurar',
    'Aliviou? Calma aí quer um trato que eu te dou! Mulher tu pode até falar mas, foi assim que tu gostou!',
    'Ela achou meu cabelo engraçado',
    'Proibida pra mim no way',
    'Disse que não podia ficar',
    'Mas levou a sério o que eu falei',
    'Eu vou fazer de tudo que eu puder',
    'Eu vou roubar essa mulher pra mim',
    'Eu posso te ligar a qualquer hora',
    'Mas eu nem sei seu nome!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'Eu me flagrei pensando em você',
    'Em tudo que eu queria te dizer',
    'Numa noite especialmente boa',
    'Não há nada mais que a gente possa fazer',
    'Eu vou fazer de tudo que eu puder',
    'Eu vou roubar essa mulher pra mim',
    'Eu posso te ligar a qualquer hora',
    'Mas eu nem sei seu nome!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'Se não eu, quem vai fazer você feliz?',
    'Se não eu, quem vai fazer você feliz? Guerra!',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skateskate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skateskate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skateskate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate',
    'skate'];
  }
}
